version: '3.2'
services:
    percona-5.7:
      image: percona:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: true
      ports:
        - 3306:3306
      command: mysqld --log-bin=mysql-bin.log --server-id 1 --binlog-format=row --gtid_mode=on --enforce-gtid-consistency=on --log_slave_updates

    percona-5.7-ctl:
      image: percona:5.7
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: true
      ports:
        - 3307:3307
      command: mysqld --log-bin=mysql-bin.log --server-id 1 --binlog-format=row --gtid_mode=on --enforce-gtid-consistency=on --log_slave_updates -P 3307

#    mysql:
#      image: mysql:5.7.12
#      command: --local-infile --datadir=/var/lib/mysql --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog_do_db=cdc
#      environment:
#        MYSQL_DATABASE: pymysqlreplication_test
#        MYSQL_ALLOW_EMPTY_PASSWORD: true
#      ports:
#        - "3306:3306"